language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor/

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  #- composer global require squizlabs/php_codesniffer --no-suggest

install:
  - composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.3"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
  - |
    cd tests
    codecept build
    cd ..

before_script:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  - php -m
  - 'export PATH="${PATH}:${HOME}/.composer/vendor/bin"'
  - cat tests/ldapconfig.ini.dist | sed s/389/3389/ > tests/ldapconfig.ini
  - mkdir /tmp/slapd
  - slapd -f tests/ldif_data/slapd.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/ldif_data/base.ldif
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/ldif_data/INITIAL_TESTDATA.ldif

script:
  - |
    chmod -R 0777 tests/runtime
    cd tests/web
    chmod -R 0777 assets
    php -S localhost:8080 > /dev/null 2>&1 &
    cd ..
    codecept run --coverage --coverage-xml
    cd ..

after_script:
  #- vendor/bin/test-reporter --coverage-report=tests/codeception/_output/coverage.xml

env:
  global:
    secure:
      Oaoj1V2Cx/jqv3YIDDxV1qlberAkDJIkCzdl4a1aXtskJ6dsaFRJsltmX20XzajZvC7hRQgIYVDiOmZAwSTa717B4rt6QyLNqKJeRL7fOZeQAWf88DgXKyG/XukURlFLhxldIUXo4VMT8iCIFlvWK5LSrRG4D99qzb8ZepE4otvmu1fy67B4AncqYXp9NrrkyDpRyanDYq8zSy9us3tl+dUz1h5sFPjI3Sf0GR9BFcAwezaAhWMoKH5c9YML4oQNJuLsMTcNxYrJ49zqe3c67qqEVckM23+OU0qeuyINTD9vBLB2HNOLEm+J7Zr8ZdKhb3XKpDKeqtowAIA7ccGFGnOn6W4/SEB8iyO7v3xgWYyvdqKjLSzQaUhStfllXDRX+89WXunjo9pH0o1dUSil6/YtB6krDRqlbKwqIlow7pw6tTtO5KslOZqEEblsOT0bAG88njmBu8f6UnlK9uVhaOi2hKGP40Yerao/Y0thiX/A1rCfnn563O86h7B0SpyTKIroqJBkgZqSqgUrufI94cetTxPu039YhBXkK9G9ibP+zXC7IzL4FHO57ExfPRLsQYrPfBK0NQD/qdlWskygBds9Ik780DbQeY/ch3YqdnmscD4JDm3snBTbTYOW8v1Q2Suy5D5CI9PpP349A851oaqHPykmK/TUl8Q05p1rZ7s=
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
  code_climate:
    repo_token:
      secure:
        eaf1FSWROdesTg2zgQiIMlX+BZaU+T5esoEQhoM8jkHIwLzLThI6U6EYUfVo3Zj1X6nNh1PykSDyaT/J/CTyhDtf8kDlPRzYThPKXtsoxaMghmmZ1nJGfrd25oHTBRsKx8ZpOxc4fN6hk/80wlyys2o5pUggNOhSQNF2xcqyGOhnTRLYRHogmNtMNotE9rJaFO1Pe1IGeK6Px/CwOrr8D38Gazl2uKuMC4imp+8Qf8sWmUaRPIdfxpQ/0f60+bKUDQ64Xnj8xorfg38yKvJHmiwYOrFKlIIbh/fZb585KuKYtwHGXhC4HjO8M/iqiskkcTwPXUXd/h5pQbAwVH5+idoAgGzHgaUMxUY0yLJSIjNOcTIFmhvreYFYwR+bYJ9hx9AAgSoSCfQZ6sI8loVqGC0Mn+MdpnD+7punIY0bsKJEHBrRzh0LStLO642EFwNORS8zqG3ypjaxwS3cDWShe/2qqBtQ4jEtDSDjWYLFSK8y6Nj/VjJMCXXwMCjIKWtOTck5D2Gu5JW+6oRGQPpHbxXeFnRsoPb9BMKWI8JIqhfQ7DIRQDKiCyH31vHlAZGXn9Y2O1YKWhEyq03OexOS6i6210tTM/ClE/ttPrzVCJ7falZzaCvhGbj8RxwIR+Oz4e/HYq+2iVtbf6iL4SAA++tPx34izTOIhCI4AxMlTv0=