language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor/

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

install:
  - composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.3"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
  - travis_retry composer global require "squizlabs/php_codesniffer=*"
  - |
    cd tests
    codecept build
    cd ..

before_script:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | if [ ! -n "$(php -m | grep ldap)" ]; then  pecl install ldap; fi;
  - php -m
  - 'export PATH="${PATH}:${HOME}/.composer/vendor/bin"'
  - cat tests/ldapconfig.ini.dist | sed s/389/3389/ > tests/ldapconfig.ini
  - mkdir /tmp/slapd
  - slapd -f tests/ldif_data/slapd_linux.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/ldif_data/base.ldif
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/ldif_data/INITIAL_TESTDATA.ldif

script:
  - |
    chmod -R 0777 tests/runtime
    cd tests/web
    chmod -R 0777 assets
    php -S localhost:8080 > /dev/null 2>&1 &
    cd ..
    codecept run --coverage --coverage-xml
    cd ..

after_script:
  - vendor/bin/test-reporter --coverage-report=tests/codeception/_output/coverage.xml

env:
  global:
    secure:
      PCqJRKn6b5T7/IKpEn3iBCTg9AmjW0bOhThp2J272+1d4QLOzFIrOdzd/ecbM6ReVMNZKUmSZr2Cf9ihr6GDGwUODpKAZpm7Mm0viuopiMq48Y4++pjTBWlNiWihm/K7H7fMKXmKwfPCTEzPSt327finAlHWP2ICeeqEvLepvUxkACIVVjY/FO/pSrQyElpW/nVolZn1zkYDGOSspMU058UFhphVbcHgvq2iY24amejd65dv1c3hwGfNzHUZSbNO8Rr6OsSk7fxPcplUFn3CK3rGnKnxZShraUg68wqW8Zai1Gqpv7XrjYtQSof3VbVDAEEPG5Qp7nhqRJb/i2slskNCcHprHWUYsEKJxXpUs44tMV/Y3WUxtzc1AYiLK3dgJTXZHdcDgrOQaNUy9cvVHraBj9BPGm9GJOy3vgx0gf7cVAe4NKYww2YI22qk97kDOcDwdHFF8VGQTXdBRGgs0yECtYASV3Lz8rc8JjgUv+sG6bt+fpnGiUiaP5IvKHyhd3A2FYTAqe2PUW8H0Qcs/G+TeootBsqnubGDqeUMKJRuMyjHWGzSlUXmQD9MMZJCMgTFinIw8L+ZJ5wKVPzEBgawJ1HSmtFaD+93pdFVA4/DkPYyzVj2Hm0EievrN2rgUAJ55DnSFYKFDK7GUZJXHq1X8nFErrnClWPp1gIlHtc=
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
  code_climate:
    repo_token:
      secure:
        eaf1FSWROdesTg2zgQiIMlX+BZaU+T5esoEQhoM8jkHIwLzLThI6U6EYUfVo3Zj1X6nNh1PykSDyaT/J/CTyhDtf8kDlPRzYThPKXtsoxaMghmmZ1nJGfrd25oHTBRsKx8ZpOxc4fN6hk/80wlyys2o5pUggNOhSQNF2xcqyGOhnTRLYRHogmNtMNotE9rJaFO1Pe1IGeK6Px/CwOrr8D38Gazl2uKuMC4imp+8Qf8sWmUaRPIdfxpQ/0f60+bKUDQ64Xnj8xorfg38yKvJHmiwYOrFKlIIbh/fZb585KuKYtwHGXhC4HjO8M/iqiskkcTwPXUXd/h5pQbAwVH5+idoAgGzHgaUMxUY0yLJSIjNOcTIFmhvreYFYwR+bYJ9hx9AAgSoSCfQZ6sI8loVqGC0Mn+MdpnD+7punIY0bsKJEHBrRzh0LStLO642EFwNORS8zqG3ypjaxwS3cDWShe/2qqBtQ4jEtDSDjWYLFSK8y6Nj/VjJMCXXwMCjIKWtOTck5D2Gu5JW+6oRGQPpHbxXeFnRsoPb9BMKWI8JIqhfQ7DIRQDKiCyH31vHlAZGXn9Y2O1YKWhEyq03OexOS6i6210tTM/ClE/ttPrzVCJ7falZzaCvhGbj8RxwIR+Oz4e/HYq+2iVtbf6iL4SAA++tPx34izTOIhCI4AxMlTv0=
