language: php

php:
  - 7.4
  - 8.0
  - 8.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor/

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

install:
  - composer --version
  - travis_retry composer install --dev --prefer-dist --no-interaction
  #  - travis_retry make composer-update
  - if [ -d "$HOME/.config/composer/vendor/bin" ]; then export PATH="$HOME/.config/composer/vendor/bin:$PATH"; fi
  - if [ -d "$HOME/.composer/vendor/bin" ]; then export PATH="$HOME/.composer/vendor/bin:$PATH"; fi
#  - |
#    cd tests
#    codecept build
#    cd ..

before_script:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | if [ ! -n "$(php -m | grep ldap)" ]; then  pecl install ldap; fi;
  - php -m
  - make start-ldap

script:
  - |
    make serve
    make test

#after_script:
#  - vendor/bin/test-reporter --coverage-report=tests/codeception/_output/coverage.xml

env:
  global:
    secure:
      Oaoj1V2Cx/jqv3YIDDxV1qlberAkDJIkCzdl4a1aXtskJ6dsaFRJsltmX20XzajZvC7hRQgIYVDiOmZAwSTa717B4rt6QyLNqKJeRL7fOZeQAWf88DgXKyG/XukURlFLhxldIUXo4VMT8iCIFlvWK5LSrRG4D99qzb8ZepE4otvmu1fy67B4AncqYXp9NrrkyDpRyanDYq8zSy9us3tl+dUz1h5sFPjI3Sf0GR9BFcAwezaAhWMoKH5c9YML4oQNJuLsMTcNxYrJ49zqe3c67qqEVckM23+OU0qeuyINTD9vBLB2HNOLEm+J7Zr8ZdKhb3XKpDKeqtowAIA7ccGFGnOn6W4/SEB8iyO7v3xgWYyvdqKjLSzQaUhStfllXDRX+89WXunjo9pH0o1dUSil6/YtB6krDRqlbKwqIlow7pw6tTtO5KslOZqEEblsOT0bAG88njmBu8f6UnlK9uVhaOi2hKGP40Yerao/Y0thiX/A1rCfnn563O86h7B0SpyTKIroqJBkgZqSqgUrufI94cetTxPu039YhBXkK9G9ibP+zXC7IzL4FHO57ExfPRLsQYrPfBK0NQD/qdlWskygBds9Ik780DbQeY/ch3YqdnmscD4JDm3snBTbTYOW8v1Q2Suy5D5CI9PpP349A851oaqHPykmK/TUl8Q05p1rZ7s=

addons:
  apt:
    packages:
      - ldap-utils
      - slapd
      - make
#  code_climate:
#    repo_token:
#      secure: "TtpIg9hi82LISorWNAI5oqcu0M0KR/OBzeNJMumAlUwqWlMq9rHS5RMC1gaKGh6xLSniG28WlD6qkpVe7CpT9CBfwatehgTKPVzmrBFea7onvESE4c8LYxe6vMyQNPM7J0G7wx4e64o4MZ90fw4Nd+ug+ER7EnoW9F00wW9fnRFt4U83+1zDDU7YuOaU5mM1jQr4Jj9N3Itr6oxKdjm4Zkl5SynkrnvTx3doSrL5qbR4+TuYKcV0PoUk5vnGb+JxueAAXy+B77077YZwJiElfrDkKzJwDfiH8YYM0ThZclwWLtyuW8vfTncaFbywBaIERftbDy/pEpKq2S7MCQiVXNeV5yRXO87W0W/SpTczLDZjxkb20FOMIv/UQgq6/Z+OYa9obJmxrCObHeCGWDES+5vzTLavbbe/ZrTeV5fyy7VJWCS0DQ81Z7Fh4v2n3bD0aY0UVDphLjGkwVvcL5AFAByI2VIWzsW/hZSmZNxrYrrgnwOfxn0E0t9XVIVwYUep/Px4Xlz+LCR+1xG3Lg+Fw5+xmixwkCMJTXv5p1CDYoN+Te2tvTYG+5Wk+7+JzZ9vDQkvphaSjojKQTweKPKvp0gDmjZo+LM9A6WGrv6USiqiOIGXru6xiWPKxOUI82b1Bzx8DRONhk+oxrHmVp+copL/ETUxvMu32iobzH9eX20="
