language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor/

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

install:
  - composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.3"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
  - travis_retry composer global require "squizlabs/php_codesniffer=*"
  - travis_retry composer global require "phpunit/php-timer:^1.0.6"
  - |
    cd tests
    codecept build
    cd ..

before_script:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | if [ ! -n "$(php -m | grep ldap)" ]; then  pecl install ldap; fi;
  - php -m
  - 'export PATH="${PATH}:${HOME}/.composer/vendor/bin"'
  - cat tests/ldapconfig.ini.dist | sed s/389/3389/ > tests/ldapconfig.ini
  - mkdir /tmp/slapd
  - slapd -f tests/ldif_data/slapd_linux.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/ldif_data/base.ldif
  - ldapadd -h localhost:3389 -D cn=admin,dc=example,dc=com -w test -f tests/ldif_data/INITIAL_TESTDATA.ldif

script:
  - |
    chmod -R 0777 tests/runtime
    cd tests/web
    chmod -R 0777 assets
    php -S localhost:8080 > /dev/null 2>&1 &
    cd ..
    codecept run --coverage --coverage-xml
    cd ..

after_script:
  - vendor/bin/test-reporter --coverage-report=tests/codeception/_output/coverage.xml

env:
  global:
    secure:
      Oaoj1V2Cx/jqv3YIDDxV1qlberAkDJIkCzdl4a1aXtskJ6dsaFRJsltmX20XzajZvC7hRQgIYVDiOmZAwSTa717B4rt6QyLNqKJeRL7fOZeQAWf88DgXKyG/XukURlFLhxldIUXo4VMT8iCIFlvWK5LSrRG4D99qzb8ZepE4otvmu1fy67B4AncqYXp9NrrkyDpRyanDYq8zSy9us3tl+dUz1h5sFPjI3Sf0GR9BFcAwezaAhWMoKH5c9YML4oQNJuLsMTcNxYrJ49zqe3c67qqEVckM23+OU0qeuyINTD9vBLB2HNOLEm+J7Zr8ZdKhb3XKpDKeqtowAIA7ccGFGnOn6W4/SEB8iyO7v3xgWYyvdqKjLSzQaUhStfllXDRX+89WXunjo9pH0o1dUSil6/YtB6krDRqlbKwqIlow7pw6tTtO5KslOZqEEblsOT0bAG88njmBu8f6UnlK9uVhaOi2hKGP40Yerao/Y0thiX/A1rCfnn563O86h7B0SpyTKIroqJBkgZqSqgUrufI94cetTxPu039YhBXkK9G9ibP+zXC7IzL4FHO57ExfPRLsQYrPfBK0NQD/qdlWskygBds9Ik780DbQeY/ch3YqdnmscD4JDm3snBTbTYOW8v1Q2Suy5D5CI9PpP349A851oaqHPykmK/TUl8Q05p1rZ7s=
      
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
  code_climate:
    repo_token:
      secure: "TtpIg9hi82LISorWNAI5oqcu0M0KR/OBzeNJMumAlUwqWlMq9rHS5RMC1gaKGh6xLSniG28WlD6qkpVe7CpT9CBfwatehgTKPVzmrBFea7onvESE4c8LYxe6vMyQNPM7J0G7wx4e64o4MZ90fw4Nd+ug+ER7EnoW9F00wW9fnRFt4U83+1zDDU7YuOaU5mM1jQr4Jj9N3Itr6oxKdjm4Zkl5SynkrnvTx3doSrL5qbR4+TuYKcV0PoUk5vnGb+JxueAAXy+B77077YZwJiElfrDkKzJwDfiH8YYM0ThZclwWLtyuW8vfTncaFbywBaIERftbDy/pEpKq2S7MCQiVXNeV5yRXO87W0W/SpTczLDZjxkb20FOMIv/UQgq6/Z+OYa9obJmxrCObHeCGWDES+5vzTLavbbe/ZrTeV5fyy7VJWCS0DQ81Z7Fh4v2n3bD0aY0UVDphLjGkwVvcL5AFAByI2VIWzsW/hZSmZNxrYrrgnwOfxn0E0t9XVIVwYUep/Px4Xlz+LCR+1xG3Lg+Fw5+xmixwkCMJTXv5p1CDYoN+Te2tvTYG+5Wk+7+JzZ9vDQkvphaSjojKQTweKPKvp0gDmjZo+LM9A6WGrv6USiqiOIGXru6xiWPKxOUI82b1Bzx8DRONhk+oxrHmVp+copL/ETUxvMu32iobzH9eX20="
